//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class ban
    {
        public int BanID { get; set; }
        public string PlayerName { get; set; }
        public string Reason { get; set; }
        public System.DateTime BannedDateTime { get; set; }
        public string Admin { get; set; }
        public Nullable<System.DateTime> BannedUntil { get; set; }
        public bool IsPermanentBan { get; set; }
        public bool IsCurrentlyBanned { get; set; }
        public string IpAddresses { get; set; }
        public Nullable<System.DateTime> ModifiedDateTime { get; set; }
        public string ModifiedByAdmin { get; set; }
    }
}
