//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class bans
    {
        public int id { get; set; }
        public int botid { get; set; }
        public string server { get; set; }
        public string name { get; set; }
        public string ip { get; set; }
        public System.DateTime date { get; set; }
        public string gamename { get; set; }
        public string admin { get; set; }
        public string reason { get; set; }
    }
}
