//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dotaplayers
    {
        public int id { get; set; }
        public int botid { get; set; }
        public int gameid { get; set; }
        public int colour { get; set; }
        public int kills { get; set; }
        public int deaths { get; set; }
        public int creepkills { get; set; }
        public int creepdenies { get; set; }
        public int assists { get; set; }
        public int gold { get; set; }
        public int neutralkills { get; set; }
        public string item1 { get; set; }
        public string item2 { get; set; }
        public string item3 { get; set; }
        public string item4 { get; set; }
        public string item5 { get; set; }
        public string item6 { get; set; }
        public string hero { get; set; }
        public int newcolour { get; set; }
        public int towerkills { get; set; }
        public int raxkills { get; set; }
        public int courierkills { get; set; }
    }
}
