//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class dotagames
    {
        public int id { get; set; }
        public int botid { get; set; }
        public int gameid { get; set; }
        public int winner { get; set; }
        public int min { get; set; }
        public int sec { get; set; }
    }
}
