//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class downloads
    {
        public int id { get; set; }
        public int botid { get; set; }
        public string map { get; set; }
        public int mapsize { get; set; }
        public System.DateTime datetime { get; set; }
        public string name { get; set; }
        public string ip { get; set; }
        public int spoofed { get; set; }
        public string spoofedrealm { get; set; }
        public int downloadtime { get; set; }
    }
}
