//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.DB
{
    using System;
    using System.Collections.Generic;
    
    public partial class w3mmdvars
    {
        public int id { get; set; }
        public int botid { get; set; }
        public int gameid { get; set; }
        public int pid { get; set; }
        public string varname { get; set; }
        public Nullable<int> value_int { get; set; }
        public Nullable<double> value_real { get; set; }
        public string value_string { get; set; }
    }
}
