//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Fate.DB.Entity
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class frsEntities : DbContext
    {
        public frsEntities()
            : base("name=frsEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<game> game { get; set; }
        public virtual DbSet<gameplayerdetail> gameplayerdetail { get; set; }
        public virtual DbSet<herotype> herotype { get; set; }
        public virtual DbSet<herotypename> herotypename { get; set; }
        public virtual DbSet<player> player { get; set; }
        public virtual DbSet<playerherostat> playerherostat { get; set; }
        public virtual DbSet<playerstat> playerstat { get; set; }
        public virtual DbSet<ranking> ranking { get; set; }
        public virtual DbSet<server> server { get; set; }
    }
}
